### ISSUE TITLE
MacOS - Accessing attributes of MPV object

### ISSUE THREAD

**Issue by willwrong** [kpj/Vydia#1]
Greetings,

This may be a long shot, but I'm trying to implement your macOS MPV wrapper (https://github.com/kpj/Vydia/blob/master/vydia/extra/macos_mpv_wrapper.py) and while it allows me to play a video in a window, and switch between videos, it doesn't appear to allow me to access/modify any of the player's attributes. If you can recall how this works, would you have any ideas to point me in the right direction? 

Thanks you and all the best.

**Comment by kpj** [comment]
If I understand you correctly, the `player` variable used in `MPVProxy._run` should help you with that.
But since you closed the issue, I assume you have found a solution :-)
